m-lab/ndt-e2e-clientworker

- client_wrapper/client_wrapper.py
- client_wrapper/html5_driver.py
- tests/test_html5_driver.py
This adds a simple command line interface to client_wrapper
This also makes a slight change to NdtHtml5SeleniumDriver's semantics in
that now the perform_test() call has no arguments. This allows us to use
a consistent perform_test() call across different drivers (including
browserless clients).
Note that, at this point, all CLI output (everything in the main() function) is
just placeholder and likely will change in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/4)
> Adds a simple CLI to client_wrapper

- client_wrapper/client_wrapper.py
- client_wrapper/html5_driver.py
- client_wrapper/results.py
- tests/test_html5_driver.py
Implemented `NdtSingleTestResult` -- `NdtResult` now stores `NdtSingleTestResult` objects, rather than storing the values directly. Also converted values so they are in Mb/s where necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/6)
> Html5 driver implementation of `NdtSingleTestResult`

- client_wrapper/client_wrapper.py
- client_wrapper/html5_driver.py
- client_wrapper/names.py
This change pulls all the name constants (for NDT clients, browsers, OSes)
into a separate file of just constants. This eliminates string duplication
and reduces the risk of string mismatches (e.g. 'ndtjs' vs 'ndt_js').
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/8)
> Refactor name constants into a specific name module

- client_wrapper/result_encoder.py
- client_wrapper/results.py
- tests/test_result_encoder.py
This adds a partial implementation of NdtResultEncoder that encodes test
start time, end time, and errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/7)
> Adding a JSON encoder for NdtResult

- client_wrapper/canonicalize.py
- client_wrapper/names.py
- tests/test_canonicalize.py
This adds functionality to canonicalize OS and browser names into common,
canonical formats used in client_wrapper's output filenames.
See the [design doc section](https://docs.google.com/document/d/16b0EesUFrt8eZ1T_f0wPkhC3qkG3W0o8RT4K5_8I9KE/edit#heading=h.khz5pfiy3nt4) on output filenames for additional context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/9)
> Adding support for OS and browser canonicalization

- .pylintrc
- .travis.yml
- build
- client_wrapper/html5_driver.py
- third_party/docstringchecker/LICENSE
- third_party/docstringchecker/README.md
- third_party/docstringchecker/lint.py
Adding automatic docstring style checking
* Adds automatic docstring style checks to the build script.
* Also fixes a minor docstring error in html5_driver.py.
Looking for validation of the following:
* Third-party code is placed in a reasonable location
* I have done due diligence in attributing third-party code in accordance with the code's license
* It is clear where the third-party code comes from and how to update it
* The whitelisted pylint checks are clear and desirable checks for our team
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/12)
> Adding docstring checker

- client_wrapper/filename.py
- tests/test_filename.py
Adds a filename module that generates output filenames based on the values
of an NdtResult instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/13)
> Adding support for result filename generation

- client_wrapper/result_encoder.py
- client_wrapper/results.py
- tests/test_result_encoder.py
Finishes the implementation of NdtResultEncoder so that it encodes all the
fields of an NdtResult object.
Fixes some small documentation errors in NdtResult's docstring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/16)
> Completing implementation of NdtResultEncoder

- build
This is an install script for dependencies and we don't really want it
considered under code coverage.
> Excluding selenium install script from code coverage settings

- client_wrapper/canonicalize.py
- client_wrapper/filename.py
- client_wrapper/os_metadata.py
- tests/test_canonicalize.py
- tests/test_filename.py
- tests/test_os_metadata.py
Adding a module to gather OS information. This detects the OS of the host
system and returns a os, version pair.
Also fixes a few places where we had the expected OS version strings wrong
for OS X El Capitan (should be 10.11.x) and Windows 10 (should just be 10).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/19)
> Adding OS metadata wrapper

- client_wrapper/client_wrapper.py
- client_wrapper/html5_driver.py
This commit ties several previous commits together to allow the user to
save NDT results to an appropriately named output file containing the results
serialized to JSON format.
Note that _jsonify_result and _save_result do *not* have unit test coverage
currently. I started to implement it, then realized we'd be mocking out like
8 interfaces to test a 4 line function and it seemed excessive, but let me
know if you think these are worth testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/21)
> Tying everything together to save output

- tests/test_html5_driver.py
Refactoring mainly to get rid of custom-defined mock objects and replace them with uses
of the Mock library.
This should *not* introduce any significant changes in functionality. There are *some*
changes in functionality, including removing instances of autospec=True when there was
nothing to autospec and deleting mock behavior that was not relevant to the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/22)
> Refactoring NDT HTML5 driver unit tests

- client_wrapper/canonicalize.py
- client_wrapper/names.py
- tests/test_filename.py
This adds support for saving results from a Windows Server 2012 R2 system. It initially was
not a supported platform, but supporting it facilitates testing because Win10 is not
not available in GCE, whereas Server 2012 R2 is, so this lets us test on GCE as well as
our testbed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/24)
> Adding support for Windows Server 2012 R2

- client_wrapper/html5_driver.py
- client_wrapper/results.py
- tests/test_result_encoder.py
This cleans up TestError semantics so it's a bit easier to for clients to
construct a TestError in the common case, which is to assign the timestamp
to the current UTC time. Updating unit tests to match.
Also makes TestError's fields read-only via property decorators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/23)
> Tidying up TestError semantics

- tests/test_html5_driver.py
Further refactoring of HTML5 driver's unit test. In particular:
* Creates a default mock DOM in the setUp method so that each test doesn't have
to redundantly create the elements.
* Adds a assertErrorMessagesEqual to simplify the syntax of checking error
messages.
* Adds explicit checks on the results to verify that they are either explicitly
None when we expect no value for a particular field or that they have the
correct value when we expect successful parsing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/25)
> Refactoring unit tests for HTML5 driver

- client_wrapper/html5_driver.py
- tests/test_html5_driver.py
The _populate_metric_values function is designed to catch timeout exceptions,
but it doesn't do anything that could cause a timeout exception, so this
check is unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/29)
> Fixing populate_metric_values to assume no timeouts

- client_wrapper/html5_driver.py
- tests/test_html5_driver.py
This modifies the code so that if it encounters a throughput unit on the
results page that isn't one of (Gbps, Mbps, kbps), it logs the error in the
results, but it is not a fatal exception that crashes the program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/30)
> Gracefully handling invalid throughput units

- client_wrapper/html5_driver.py
- client_wrapper/results.py
- test_requirements.txt
- tests/test_html5_driver.py
This makes a few changes to recording timestamps during the test that are a
bit intermixed in the code:
1. Changes recording of start time and end time so that they record when the
underlying client process began and ended, not when the the actual tests began
(the revised behavior matches the spec).
2. Changes recording of s2c/c2s end_time values so that it actually waits for the
element it's waiting for before recording the time (it would previously record
the time without waiting, which was a bug and caused it to record incorrect
times).
In addition, refactors html_driver a bit so that there is less mixing of
abstraction layers within functions.
Lastly, deletes the freezegun unit test as it was not providing additional
coverage over the final timing test and it's an additional unneeded …
> Fixing time logging in HTML5 driver

- client_wrapper/result_decoder.py
- client_wrapper/results.py
- requirements.txt
- tests/test_result_decoder.py
- tests/test_result_encoder.py
Adds a JSON decoder so we can decode test results. Also adjusts the semantics
of the NdtResult & friends classes so they print better debug information
and support equality comparisons.
The client wrapper will not likely use this decoder directly, but it's
implemented here because consumers will need a way of decoding the JSON
output that the client wrapper produces and it seems easiest to have it
implemented once here rather than expect consumers to figure out how to
decode the JSON properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/33)
> Adding a JSON decoder for NdtResult objects

- client_wrapper/fake_mlabns.py
- tests/test_fake_mlabns.py
For clients with mlab-ns requests baked in, we need a way of gracefully
directing those clients to a server of our choosing. With a fake mlab-ns
server, we can use DNS rewrites or HTTP response modifications to sub in
our own mlab-ns server in place of mlab-ns prod, then serve the client
a custom server FQDN.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/34)
> Adding a fake mlab-ns server implementation

- client_wrapper/fake_mlabns.py
- tests/test_fake_mlabns.py
CORS support is needed if, for example, we have a web server on
localhost:8123 that wants to refer the client to a fake mlab-ns server on
localhost:8321. Without a CORS header, this is considered a violation of
same origin policy and the browser would block the response.
Adding CORS better simulates real mlab-ns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/35)
> Adding CORS support to fake mlab-ns server

- hooks/README.md
This small change to allows the pre-commit hook example command to run multiple times. Without this fix, the `rm -rf` will delete the files under the hooks directory. With this fix, the symbolic link is removed instead of the files in the hooks directory.
> Allow pre-commit example run multiple times

- README.md
- client_wrapper/client_wrapper.py
- client_wrapper/http_server.py
- client_wrapper/names.py
- tests/test_http_server.py
Creates a replay HTTP server meant for replaying HTTP traffic. This is
useful for NDT clients that are hosted in complex web applications, where
it is not trivial to extract the NDT test into simple static files we could
host with something like SimpleHTTPServer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/36)
> Creates a replay HTTP server

- client_wrapper/browser_client_common.py
- client_wrapper/html5_driver.py
- tests/test_browser_client_common.py
- tests/test_html5_driver.py
Refactoring the create_browser function to a common module for shared
functions among browser-based NDT tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/39)
> Refactoring create_browser function to common module

- client_wrapper/http_server.py
There is a race condition in ReplayHTTPServer in that one thread needs to
execute serve_forever, which blocks forever, but other threads need to know
that it has started serving.
I wasn't able to figure out a way to eliminate the race condition
completely, but I believe this reduces the impact to the point that it is
fixed for practical purposes. In practice, there will be a delay of several
milliseconds between the client making an HTTP request to the replay server
then making another HTTP request to the fake mlab-ns server.
This is mainly to fix flakiness in unit tests (issue #43), which it appears
to fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/44)
> Reducing impact of race condition in ReplayHTTPServer

- client_wrapper/banjo_driver.py
- client_wrapper/html5_driver.py
- client_wrapper/results.py
- tests/test_banjo_driver.py
Adds a partial selenium driver for the Banjo client. Adds a unit test for
the currently implemented functionality.
Also fixes a minor issue with the TestResult constructor. It turns out that
using the default parameter of [] was causing all instances that used that
constructor to share the same list, which breaks unit tests. This fixes
the constructor and both client drivers' usage of the constructor.
The Banjo driver differs from the HTML5 driver in that the Banjo driver
uses a private _BanjoUiFlowWrapper so that it doesn't keep having to
pass around the "driver" and "result" parameters to different module-
level functions, but perform_test still is idempotent, which was the reason
the HTML5 driver didn't use instance variables to pass around data
in the first place. We should eventually …
> Adding a partial implementation of the Banjo driver

- client_wrapper/banjo_driver.py
- client_wrapper/results.py
- tests/test_banjo_driver.py
Adds functionality to the Banjo driver to allow it to record the relevant
event times of the test.
Also fixes a small bug in results.NdtResult where the constructor was
assigning default values that got re-used between calls (breaking tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/48)
> Adding event time recording to Banjo driver

- client_wrapper/banjo_driver.py
- client_wrapper/client_wrapper.py
- tests/test_banjo_driver.py
Adds logic to banjo client driver to locate and parse fields from the test
results page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/49)
> Adds results parsing logic to banjo driver

- client_wrapper/client_wrapper.py
The if should be an elif, otherwise we always raise a spurious ValueError
when Banjo is the selected client.
> Fixes a missing elif

- client_wrapper/banjo_driver.py
- tests/test_banjo_driver.py
Adds graceful handling for the case when the latency field of the results
page has no value. Adds unit tests to verify graceful handling of empty values
for latency, download throughput, and upload throughput.
Changes the error message for unexpected values slightly to make it clearer
in the case of blank field values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/54)
> Adding handling for blank latency field

- client_wrapper/banjo_driver.py
- client_wrapper/browser_client_common.py
- client_wrapper/html5_driver.py
- tests/ndt_client_test.py
- tests/ndt_client_testcase.py
- tests/test_banjo_driver.py
- tests/test_browser_client_common.py
- tests/test_html5_driver.py
This fixes a bug in that the client_wrapper was just calling close() on
the Selenium driver, which closes the browser window, but does not free
resources associated with the browser driver. To do that, we need to call
quit().
This changes create_browser to a context manager so that callers can call
it in a with block that automatically calls quit() at the end. Updates the
unit tests to match.
Small refactoring of apply_patches_for_create_browser so that it's now shared
between both the banjo tests and the HTML5 tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/55)
> Fixing client wrapper so it always quit()s Selenium

- client_wrapper/banjo_driver.py
- client_wrapper/browser_client_common.py
- client_wrapper/html5_driver.py
- tests/test_browser_client_common.py
Microsoft's WebDriver for edge places the browser version information in the
'browserVersion' field instead of the 'version' field. This adds a function
that checks both fields if a 'version' field is not present and refactors
both the banjo and HTML5 clients to use this function instead of reading the
'version' field directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/57)
> Fixing driver version check to work with Microsoft Edge

- client_wrapper/banjo_driver.py
- tests/test_banjo_driver.py
This fixes a crash in the banjo driver that occurred when load_url failed.
The failure would cause perform_test to return None, but callers expect it
to return a populated NdtResult object.
This fixes perform_test so that it always returns a populated NdtResult
even if load_url fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/62)
> Fixing a crash in banjo driver

- client_wrapper/http_server.py
- tests/test_http_server.py
The ReplayHTTPServer had an issue in that when it started up, it wouldn't
necessarily be serving HTTP requests yet because it started the actual
servers in background threads. This change explicitly waits until the
background threads are actually serving HTTP requests before returning.
Note: This is an uglier and more convoluted solution than I want, but it's
the best thing I can think of. I'm open to other solutions that eliminate
this race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/59)
> Fixing race condition in HTTPReplayServer

- client_wrapper/client_wrapper.py
This corrects the URL path for the banjo driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/65)
> Fixing banjo URL path

- client_wrapper/results.py
- tests/test_results.py
This fixes a bug in the constructor for TestError. It turns out that the
default value of a function argument is an object, all callers share that
same object. This is undesirable for the TestError because each call should
result in a new timestamp of the current time.
This fixes the shared object and adds a unit test for the issue.
This fixes #60.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/64)
> Fixing a bug in TestError timestamp calculation

- client_wrapper/banjo_driver.py
- client_wrapper/client_wrapper.py
- client_wrapper/fake_mlabns.py
- client_wrapper/html5_driver.py
This adds fine grained logging to the client wrapper. Specifically:
* Adds logging to the NDT HTML5 client wrapper
* Adds logging to the banjo driver
* Adds logging to fake mlab-ns
* Adds logging to top-level CLI module
A few notes:
We use the INFO level rather than the DEBUG level because once we use DEBUG,
Selenium's debug-level logging floods the logs. It might be possible to do
per-module debug-level, but for simplicity, it seemed easiest to start with
INFO.
There's a lot of redundancy in the logging in html5_driver.py. I didn't try
too hard to eliminate it because I expect that once we refactor html5_driver
to the same structure as banjo_driver, the logging will be as easy as it is
in banjo_driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" …
> Adding fine-grained logging

- client_wrapper/http_response.py
- requirements.txt
- tests/test_http_response.py
Adds a class to represent an HTTP response.
We will use this class as part of the native replacement for mitmdump, as it
provides a way of capturing HTTP responses, then saving them in YAML format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/71)
> Adding HTTP response class

- build
- replay_generator/README.md
- replay_generator/replay_generator.py
This continues the process of replacing the mitmdump dependency. This adds a
script that launches an HTTP proxy that captures traffic and writes it to a
YAML file so that it can be replayed locally.
There are deliberately no unit tests because they'd be fairly complex and this
feels like a utility script more than part of the core application, but we
can add unit tests if necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/72)
> Adding an HTTP replay generator

- replay_generator/replay_generator.py
Fixing a bug in replay_generator. It's processing the response data, but then
saving the original data instead of the processed data. This fixes the
generator so that it saves the processed data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/75)
> Fixing replay generator to save processed data

- client_wrapper/banjo_driver.py
- tests/test_banjo_driver.py
Added an explicit wait in the banjo driver for waiting until the "Run Test" button is visible before attempting to click it. Allows the driver to gracefully handle not finding the button. 
Addresses this issue: 
https://github.com/m-lab/ndt-e2e-clientworker/issues/68
> Banjo RunTest Button 

- client_wrapper/banjo_driver.py
- client_wrapper/browser_client_common.py
- client_wrapper/client_wrapper.py
- client_wrapper/html5_driver.py
- tests/test_html5_driver.py
Instead of using 20 seconds as the timeout for everything, this uses more
granular timeouts for different aspects of the UI flow. This should improve
performance in the cases where the server is in a bad state and everything
is timing out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/80)
> Reducing UI timeouts from a global 20 seconds to more granular timeouts

- client_wrapper/client_wrapper.py
- client_wrapper/html5_driver.py
- tests/test_html5_driver.py
This parameter is actually unnecessary. It was originally added for the HTML5
client, which needs a URL rather than a server, but the URL of the HTML5
client can be deduced, given the server FQDN.
Eliminating the client_url parameter simplifies semantics and allows similar
parameters to be used across different client types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/84)
> Removing client_url parameter

- client_wrapper/html5_driver.py
Refactoring the HTML5 driver to use a private helper class so that the
functions are not all passing around the same set of variables all the time.
This brings the HTML5 driver closer in style to the banjo driver.
This is a non-functional change (pure refactoring) so does not require any
changes to the unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/86)
> Refactoring HTML5 driver

- client_wrapper/client_wrapper.py
Changed the path we run tests against on the local replay server. 
Also in an unrelated change I made output a required argument because when I was testing the new replay file, an error would occur when the output path was not specified.
> Altered the banjo client path to work with the new replay file. 

- client_wrapper/http_server.py
- tests/test_http_server.py
We managed to get a good HTTP replay file from the production Google Search site, but E2E for OneBox was still broken for some reason. Investigating, Fernanda and I discovered that the OneBox client was no longer querying mlab-ns with just `/ndt` or `/ndt_ssl`, but instead with `/ndt_ssl?policy=geo_options`. This caused [the current http_server.py function](https://github.com/fernandalavalle/ndt-e2e-clientworker/blob/public_replay/client_wrapper/http_server.py#L101) for rewriting mlab-ns responses to miss rewriting the response to point to our testing server.
Since we have no control over how the OneBox client queries mlab-ns, this PR assumes that any requests that begins with `/ndt` is an mlab-ns query.
Additional, rather than rewriting the entire mlab-ns request, this PR modifies the …
> Fix mlab-ns rewriting in http replay server.

- replay_generator/replay_generator.py
Most of the data returned from OneBox client requests is javascript, and some of that javascript fetches yet additional resources, and some of that over HTTPS, which our current replay_generator doesn't handle. This PR adds another explicit domain to the list of client request domains that need to be substituted with 127.0.0.1. 
The underlying issue is that testbed clients do not have Internet access, and any request to a host not on the testbed network will fail. The javascript returned by the Google search was attempting to fetch things from https://apis.google.com, which was failing, causing the replay server request from the E2E client to never completely load, causing OneBox tests on Firefox and Safari to fail with timeout errors.
It should be noted that OneBox tests on Chrome always …
> Substitutes all instances of the domain apis.google.com with 127.0.0.1.

- tests/test_os_metadata.py
We've upgraded the MacOS client in the testbed from version Capitan to Sierra. This PR fixes the only reference to "capitan" that I could find in this repository.
> Updates one unit test to check the MacOS version number for Sierra instead of Capitan.
